### ISSUE TITLE
First Join Command Error

### ISSUE THREAD

**Issue by Jaimss** [Jaimss/moducore#67]
```
[04:23:33 ERROR]: [ModuCoreBukkit] This is not an error of MCCoroutine! See sub exception for details.
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.extension.ExtensionKt.invokeSuspend(Extension.kt:10) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.EventServiceImpl$SuspendingEventExecutor$executeEvent$1.invokeSuspend(EventServiceImpl.kt:177) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.EventServiceImpl$SuspendingEventExecutor$executeEvent$1.invoke(EventServiceImpl.kt) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.CoroutineSessionImpl$launchInternal$1$1.invokeSuspend(CoroutineSessionImpl.kt:99) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.CoroutineSessionImpl$launchInternal$1$1.invoke(CoroutineSessionImpl.kt) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.CoroutineSessionImpl$launchInternal$1.invokeSuspend(CoroutineSessionImpl.kt:98) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.dispatcher.MinecraftCoroutineDispatcher.dispatch(MinecraftCoroutineDispatcher.kt:25) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:322) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.BuildersKt__Builders_commonKt.startCoroutineImpl(Builders.common.kt:193) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.BuildersKt.startCoroutineImpl(Unknown Source) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:134) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.CoroutineSessionImpl.launchInternal(CoroutineSessionImpl.kt:94) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.CoroutineSessionImpl.launch(CoroutineSessionImpl.kt:82) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.EventServiceImpl$SuspendingEventExecutor.executeEvent(EventServiceImpl.kt:174) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.EventServiceImpl$SuspendingEventExecutor.execute(EventServiceImpl.kt:159) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:666) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:365) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:307) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:326) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:568) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:232) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1583) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1416) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1189) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:304) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsupportedOperationException
        at java.util.Collections$UnmodifiableCollection.addAll(Collections.java:1077) ~[?:?]
        at dev.jaims.moducore.bukkit.listener.PlayerJoinListener.onJoin(PlayerJoinListener.kt:116) ~[moducore-bukkit-0.7.2-b131.jar:?]
        ... 39 more
[04:23:33 INFO]: (!) Void4x8 has logged in!
```

**Comment by Jaimss** [comment]
#68
