### ISSUE TITLE
/ping error

### ISSUE THREAD

**Issue by Jaimss** [Jaimss/moducore#71]
Via Void on Discord:
```
[07:22:16 ERROR]: [ModuCoreBukkit] This is not an error of MCCoroutine! See sub exception for details.
java.lang.NoSuchFieldException: ping
        at java.lang.Class.getField(Class.java:2117) ~[?:?]
        at dev.jaims.moducore.bukkit.command.PingCommand.execute(PingCommand.kt:63) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.bukkit.command.BaseCommand$DefaultImpls.onCommand(BaseCommand.kt:126) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.bukkit.command.PingCommand.onCommand(PingCommand.kt:42) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.bukkit.command.BaseCommand$register$command$1$execute$1.invokeSuspend(BaseCommand.kt:138) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.bukkit.command.BaseCommand$register$command$1$execute$1.invoke(BaseCommand.kt) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.bukkit.command.BaseCommand$register$command$1$execute$1.invoke(BaseCommand.kt) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.CoroutineSessionImpl$launchInternal$1$1.invokeSuspend(CoroutineSessionImpl.kt:99) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.CoroutineSessionImpl$launchInternal$1$1.invoke(CoroutineSessionImpl.kt) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.CoroutineSessionImpl$launchInternal$1.invokeSuspend(CoroutineSessionImpl.kt:98) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.dispatcher.MinecraftCoroutineDispatcher.dispatch(MinecraftCoroutineDispatcher.kt:25) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:322) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.BuildersKt__Builders_commonKt.startCoroutineImpl(Builders.common.kt:193) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.BuildersKt.startCoroutineImpl(Unknown Source) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:134) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.CoroutineSessionImpl.launchInternal(CoroutineSessionImpl.kt:94) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.service.CoroutineSessionImpl.launch(CoroutineSessionImpl.kt:82) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.libs.com.github.shynixn.mccoroutine.ExtensionKt.launch(Extension.kt:88) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at dev.jaims.moducore.bukkit.command.BaseCommand$register$command$1.execute(BaseCommand.kt:137) ~[moducore-bukkit-0.7.2-b131.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2377) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2148) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1360) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1337) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1330) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1464) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1189) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:304) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Jaimss** [comment]
[00:35:35 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'ping' in dev.jaims.moducore.bukkit.command.BaseCommand$register$command$1(ping)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2147) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-61]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchFieldException: ping
        at java.lang.Class.getField(Class.java:2117) ~[?:?]
        at dev.jaims.moducore.bukkit.command.PingCommand.execute(PingCommand.kt:63) ~[moducore-bukkit-0.7.3.jar:?]
        at dev.jaims.moducore.bukkit.command.BaseCommand$DefaultImpls.onCommand(BaseCommand.kt:126) ~[moducore-bukkit-0.7.3.jar:?]
        at dev.jaims.moducore.bukkit.command.PingCommand.onCommand(PingCommand.kt:42) ~[moducore-bukkit-0.7.3.jar:?]
        at dev.jaims.moducore.bukkit.command.BaseCommand$register$command$1.execute(BaseCommand.kt:136) ~[moducore-bukkit-0.7.3.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 16 more
